# Generated by Django 4.0 on 2022-02-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='STAFF_PERSONAL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=30)),
                ('staff_age', models.IntegerField()),
                ('staff_contact', models.CharField(max_length=10)),
                ('staff_email', models.EmailField(max_length=30)),
                ('staff_department', models.CharField(choices=[('ComputerScience', 'CSE'), ('Electrical', 'ECE'), ('Mechanical', 'MECH'), ('BioTechnology', 'BIOTECH')], max_length=30)),
            ],
            options={
                'ordering': ('-staff_age',),
            },
        ),
    ]
